### ISSUE TITLE
Fan speed control is not exported through gsh

### ISSUE THREAD

**Issue by pfn** [NorthernMan54/homebridge-hampton-bay#3]
Google assistant can't access fan speed control, it only appears as an on/off device. Not sure if this is a gsh or this plugin issue.

**Comment by pfn** [comment]
https://github.com/actions-on-google/smart-home-nodejs/issues/238

Related to oznu/homebridge-gsh#15 and oznu/homebridge-gsh#58

**Comment by NorthernMan54** [comment]
Switch to Alexa, I can confirm it works

**Comment by pfn** [comment]
I'm already invested in the Google ecosystem. Will have to figure out how to make it work on my own.
